language: java
jdk: oraclejdk9
services:
- docker
env:
  matrix:
  - COVERAGE=0.05 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.14 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.36 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.12 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.31 BUILD_TARGET=./monolithic/repository/user
  global:
    secure: SEyai3EmLT60Q00DiDj9FQXnQpzskNjsbqFWgmoIFDR5Id75ooo9r+DkmVdX8xPijGkeG3+Cb5VWK5XiLlzqtHNmH7BtcDaroeqyPCpyTicDqbET9QpAB1aSEsE32XBCAItlXavTnOUd3pCCdhyVU5LhdQ21cf9iLdMHKGnx09clkuZbJmNeaFSb0Gw8eo5gfGR1aFgvlVb+vvZ9LjGAB5aHXnjFI3328oBb9xBBmNfq8zaIDgfsNN3Z+lDZdq+Kq38Jc/IAMEZmAQMX0jLqQT6SUAAfyV8SYgLv8DSKTZE9WAXUUitnctovZvBK2sCUTlTtgAr9pfmAN1YIB99fQtkwBiPVW0NGTRaaRrfPCZKfw6a8EdDf23ybdYwT0DfqKIh4liG2ENXyau5T9n46tsetx2JrNBKI8iGi9Sfh7g154eiAXEps0nWEv30C5hHG/xiVamc/qiS9ETCcUgI85n6bGfVaXQxxTAjesIz7jPASNcDi2kGU/fGNCMeYtnmcr40K5NSrx11heofcuVitBmkepbrtqHjxflIB07kbsoI0dc6mHQgF7a2yPBQ/QwFeC+zcirSMqACiwJgq6Ve/X5NJYXjkD25YjYXVEDBW5pkdOpG0fijbrY9GNgJKHQMVPIKJo40iE09ncOPM6fIa26dMFcra0bE+DjZIhiweuFQ=
global:
- DOCKER_LOGIN=giusprog
install:
- "./gradlew clean jar"
script:
- "./gradlew -p $BUILD_TARGET check"
after_success:
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\"
    --password-stdin ;"
  on:
    all_branches: true
