language: java
jdk: oraclejdk9

env:
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.24 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.3 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.36 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.1 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.12 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.31 BUILD_TARGET=./monolithic/repository/user

install:
  - ./gradlew clean jar
script:
  - ./gradlew -p $BUILD_TARGET check
after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
